version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_install:
      - mamba install -y openbabel

conda:
  environment: requirements.yaml

sphinx:
   configuration: docs/conf.py
