name: tmos

channels:
  - conda-forge

dependencies:
    # Base depends
  - python=3.11
  - pip
  - rdkit>=2025.3.3
  - openbabel
#  - mdanalysis>=2.10.0 # Not yet released
  - mdanalysis
  - networkx
  - qcelemental
  - periodictable
  - numpy
  - deepdiff
  - py3Dmol

  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
  - nbsphinx

  - pip:
      - git+https://github.com/MDAnalysis/mdanalysis.git@develop#subdirectory=package # delete after 2.10 is released
